// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJtJ5WJfdPxro_kfIaFiWwLKPyvfgD6cU',
    appId: '1:810900868541:android:027a083397fbff75a4d6d4',
    messagingSenderId: '810900868541',
    projectId: 'wellness-app-17f47',
    storageBucket: 'wellness-app-17f47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDV8FWaP2slj6Zk41QPc53YE4sIYEpUmc',
    appId: '1:810900868541:ios:e051474b3796bb76a4d6d4',
    messagingSenderId: '810900868541',
    projectId: 'wellness-app-17f47',
    storageBucket: 'wellness-app-17f47.firebasestorage.app',
    androidClientId: '810900868541-57eukvl9rif6nrvu0mgms8k7kuk11m7l.apps.googleusercontent.com',
    iosClientId: '810900868541-sinf0st46guna08ajumlekglst0qtfup.apps.googleusercontent.com',
    iosBundleId: 'com.islington.wellnessApp',
  );
}
